### ISSUE TITLE
nid是必要的？

### ISSUE THREAD

**Issue by shook2012** [lynxcat/micrometer-registry-nightingale#1]
没有配置nid，就NumberFormatException了。

**Comment by lynxcat** [comment]
endpoint 和 nid 二选一就好，我测试一下，可能代码有问题

**Comment by lynxcat** [comment]
我测试了一下，应该是你配置了auto-registry:true，这时候nid是必须的。因为需要注册到Nightingale中，如果不配置auto-registry，nid不是必须的

**Comment by shook2012** [comment]
### 十分感谢你的耐心回复~ 
** 发现另有两个小问题**

> 1.auto-registry属性没有配置默认值，因此，必须配置true或false，是否考虑给个你比较推荐的默认值。

> 2.nightingale 版本为 `V3.7.1，metrics上报时，返回的值是:` {"dat":"ok","err":""}` ，因此会打印如下error log

`NightingaleMeterRegistry.lambda$publish$3(99): failed to send metrics to nightingale: {"dat":"ok","err":""}`

**Comment by lynxcat** [comment]
感谢反馈
auto-registry默认值这里确实应该给个默认值的，
nightingale版本更新后返回值这个倒是没留意，之前为了省事直接对比了字符串，这两个问题晚上我修复一下

**Comment by shook2012** [comment]
赞

**Comment by shook2012** [comment]
还发现依赖方面感觉是存在些问题的，spring boot使用的是2.3.5.RELEASE，但spring-boot-starter-json，是用的2.2.13.RELEASE的版本，应该是可以统一升至相同的版本的。

**Comment by lynxcat** [comment]
这个是我本地开发环境导致的，当初开发主包的时候用的2.3.5。后来开发starter的时候改成了2.2.13。不过这个不影响的最终取决于你引入的starter-web的版本
